parameters:
#    amap_blog.example.class: Amap\BlogBundle\Example

services:
#    amap_blog.example:
#        class: %amap_blog.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
