parameters:
#    amap_panier.example.class: Amap\PanierBundle\Example

services:
#    amap_panier.example:
#        class: %amap_panier.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
