amap_commande:
    resource: "@AmapPanierBundle/Resources/config/routing/commande.yml"
    prefix:   /commande

amap_panier:
    resource: "@AmapPanierBundle/Resources/config/routing/delivery.yml"
    prefix:   /nos-paniers

amap_blog:
    resource: "@AmapBlogBundle/Resources/config/routing/article.yml"
    prefix:   /blog
    
amap_blog_image:
    resource: "@AmapBlogBundle/Resources/config/routing/image.yml"
    prefix:   /amap-blog-image

amap_main:
    resource: "@AmapMainBundle/Resources/config/routing.yml"
    prefix:   /

# amap_user:
    # resource: "@AmapUserBundle/Resources/config/routing.yml"
    # prefix:   /

            
_imagine:
    resource: .
    type:     imagine
    
fos_comment_api:
    type: rest
    resource: "@FOSCommentBundle/Resources/config/routing.yml"
    prefix: /api
    defaults: { _format: html }
    
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
 
fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile
 
fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register
 
fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting
 
fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /change-password
 
admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin
 
_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin
 
soanata_user:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix: /admin

sonata_user_impersonating:
    pattern: /
    defaults: { _controller: SonataPageBundle:Page:catchAll }
    
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
    
    
