security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512
 
    role_hierarchy:
        ROLE_MEMBER:      ROLE_USER
        ROLE_ADMIN:       [ROLE_USER, ROLE_MEMBER, ROLE_SONATA_ADMIN]
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_SONATA_ADMIN, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
        SONATA:
            - ROLE_SONATA_PAGE_ADMIN_PAGE_EDIT  # if you are not using acl then this line must be uncommented
            - ROLE_SONATA_PAGE_ADMIN_BLOCK_EDIT
 
    providers:
        fos_userbundle:
            id: fos_user.user_manager
 
    firewalls:
 
        # -> custom firewall for the admin area of the URL
        admin:
            pattern:      /admin(.*)
            form_login:
                provider:       fos_userbundle
                login_path:     /admin/login
                default_target_path: /admin/dashboard
                use_forward:    false
                check_path:     /admin/login_check
                failure_path:   /admin/login
            logout:
                path:           /admin/logout
            anonymous:    true
            switch_user:  true
        # -> end custom configuration
 
        # defaut login area for standard users
        main:
            pattern:      .*
            form_login:
                provider:       fos_userbundle
                login_path:     /login
                default_target_path: /profile
                use_forward:    false
                check_path:     /login_check
                failure_path:   null
            logout:      
                path: fos_user_security_logout
                target: /
                invalidate_session: false
            anonymous:    true
 
# ...
 
    access_control:
        - { path: ^/amap-blog-image/(update|delete), role: [ROLE_MEMBER, ROLE_ADMIN] }
        - { path: ^/blog/new, role: [ROLE_MEMBER] }
        - { path: ^/blog/.*/edit$, role: [ROLE_MEMBER, ROLE_ADMIN] }
        - { path: ^/commande, role: [ROLE_MEMBER, ROLE_ADMIN] }
        - { path: ^/create-permanence, role: [ROLE_MEMBER, ROLE_ADMIN] }
      
        # URL of FOSUserBundle which need to be available to anonymous users
        - { path: ^/_wdt, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/_profiler, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
 
        # -> custom access control for the admin area of the URL
        - { path: ^/admin/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/logout$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/login-check$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        # -> end
 
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
 
        # Secured part of the site
        # This config requires being logged for the whole site and having the admin role for the admin part.
        # Change these rules to adapt them to your needs
        - { path: ^/admin, role: [ROLE_ADMIN, ROLE_SONATA_ADMIN] }
        - { path: ^/.*, role: IS_AUTHENTICATED_ANONYMOUSLY }

